import {
    Button,
    HorizontalBox,
    VerticalBox,
    LineEdit,
} from "std-widgets.slint";

import { MyText } from "./my_text.slint";

export component MainWindow inherits Window {
    title: "我的應用";
    width: 800px;
    height: 600px;

    in property <int> count: 0;
    callback myClick;

    VerticalBox {
        padding: 24px;
        spacing: 16px;

        MyText { }

        LineEdit {
            enabled: false;
            text: root.count;
        }

        Button {
            text: "Click Me";
            clicked => {
                root.myClick();
            }
        }
    }
}
